name: Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ 386, amd64, arm, arm64 ]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: windows
          - goarch: 386
            goos: darwin
          - goarch: arm
            goos: darwin

    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.37
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "tcping"
          executable_compression: upx
          compress_assets: OFF